### ISSUE TITLE
skip_allowed input should be supported

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/secret-manager-action#5]
sometimes it's desired to skip the action if required inputs are not configured, this is especially helpful on forked repo when running github actions.

so let's add `skip_allowed` option (true) by default.

if skip_allowed=true: when one of the required inputs is not configured, skip the run step.
if skip_allowed=false: when one of the required inputs is not configured, failed the run step.

**Comment by hoatle** [comment]
actually, we don't need this feature to be implemented as we can use `if` condition of the run step, for example:

```yaml
    - name: Configure for secret-manager
      run: |
        export GIT_BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/refs\/tags\///g" \
        | sed -e "s/refs\/pull\///g" | sed -e "s/=/-/g")
        echo "::set-env name=GIT_BRANCH::$GIT_BRANCH"
        export SM_UNMASKED_KEYS='FOO, HELLO'
        echo "::set-env name=SM_UNMASKED_KEYS::$SM_UNMASKED_KEYS"
        export SM_EXPORTED_KEYS='FOO'
        echo "::set-env name=SM_EXPORTED_KEYS::$SM_EXPORTED_KEYS"

        # enable secret-manager only when CONFIG_FILE_PATH and PASSPHRASE are configured
        if [ "${CONFIG_FILE_PATH}" != '' ] && [ "${PASSPHRASE}" != '' ]; then
          echo "::set-env name=SM_ALLOWED::true"
        fi
      env:
        CONFIG_FILE_PATH: ${{ secrets.CONFIG_FILE_PATH }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - uses: ./
      if: env.SM_ALLOWED == 'true'
      id: secret-manager
      with:
        config_file_path: ${{ secrets.CONFIG_FILE_PATH }}
        passphrase: ${{ secrets.PASSPHRASE }}
        type: ${{ env.GIT_BRANCH }}
        unmasked_keys: ${{ env.SM_UNMASKED_KEYS }}
        exported_keys: ${{ env.SM_EXPORTED_KEYS }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }} # if gist:// protocol is used
```

so I'm going to revert the implementation and resolve this as won't fix.
